services:

  sonar:
    image: sonarqube:latest

    ports:
      - "9000:9000"

    networks:
      - sonar

    environment:
      - SONARQUBE_JDBC_URL=jdbc:poetgresql://dv:5432/sonar

    volumes:
      - sonarqube_conf1:/opt/sonarqube/conf1
      - sonarqube_data1:/opt/sonarqube/data
      - sonarqube_bundled-plugins1:/opt/sonarqube/lib/bundled-plugins

    depends_on:
      - db

  db:
    image: postgres:13
    networks:
      - sonar
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar

    volumes:
      - postgresql4:/var/lib/postgresql
      - postgresql_data4:/var/lib/postgresql/data
  ngrok:
    image: ngrok/ngrok:latest
    environment:
      - NGROK_AUTHTOKEN=2xalmNHwM9Bwx58DqALmJylpbrN_7dw9WzKKB28qHKayHCUV9
  
  
    command: 
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    ports:
      - 4040:4040
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    networks:
      - sonar


networks:
  sonar:

volumes:
  sonarqube_conf1:
  sonarqube_data1:
  sonarqube_extensions1:
  sonarqube_bundled-plugins1:
  postgresql4:
  postgresql_data4:
  sonarqube_extensions:
    external: false
