apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crowdfunding-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/warteen/crowndfunding-app
    targetRevision: main
    path: kebernet
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
